language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/build deploy@losyar.com:/home/www/losyarcom/ip
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_6afd0e45ce6e_key -iv $encrypted_6afd0e45ce6e_iv
  -in deploy/deploy_rsa.enc -out /tmp/deploy_rsa -d
